language: node_js

sudo: false

node_js:
  - 10

jobs:
  include:
    - stage: "linting"
      name: "Currency Exchange ES Linting"
      script: npm install && ./node_modules/.bin/eslint ./
    - stage: "testing"
      name: "NPM testing"
      script: npm install && npm test
